spring.application.name=Promocion

server.port=8092
server.servlet.context-path=/api/promociones

# Configuracion de Base de Datos
spring.datasource.url=jdbc:mariadb://40.233.27.238:3307/promotion_db
spring.datasource.username=app_user
spring.datasource.password=appSa456.
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion Flyway
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.locations=classpath:/db/migration
spring.flyway.table=schema_version_promocion
spring.flyway.validate-on-migrate=false

# Configuracion de paginacion
spring.data.web.pageable.one-indexed-parameters=true

# Configuracion Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

# Configuracion Eureka
eureka.client.service-url.defaultZone=http://localhost:8765/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# Configuracion Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=promociones-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ConfiguraciOn de Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.show-actuator=false

# Logging
logging.level.org.apache.kafka=WARN
logging.level.com.sa.promocion=DEBUG